---
title: "MB-Red"
author: "Madyson Bradford"
date: "11/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(usmap)
library(ggplot2)
library(maptools)
library(jpeg)
library(patchwork)  

data <- read.csv("")
blackbirds <- data.frame(data)
head(blackbirds)

blackbirds_transformed <- usmap_transform(blackbirds,
                                          input_names = c("Longitude","Latitude"))

map <- (plot_usmap() +
  geom_point(data = blackbirds_transformed, aes(x = x, y = y, size = Number),
             color = "red", alpha = 0.25) +
  labs(title = "Red-winged Blackbird Sightings: 2021",
       subtitle = "Data Source: JourneyNorth, University of Wisconsin-Madison Arboretum",
       caption= "Madyson Bradford --  November 2022 -- #30DayMapChallenge\nDay 11: Colour Friday: Red",
       size = "Number of Sightings") +
  theme(legend.position = "right",
        panel.background = element_rect(color = "black", fill = "lightblue")))

filepath = ""
ggsave(filepath, map, dpi = 400, height = 4, width = 6, bg="white")

```

